[tool.poetry]
name = "rubix-bacnet"
version = "0.1.0"
description = ""
authors = ["NubeDev <aidan@envrioservices.com.au>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
